Set up waitlist
valyentdev/valyent pull request #69
Opened 2023-04-04 18:39 UTC by lucaschabiron

Close #3

2023-04-04 18:56 UTC, lucas-jacques requested changes

2023-04-04 18:56 UTC, lucas-jacques commented on web/app/Controllers/Http/WaitlistController.ts
> +    if (!email) {
Use a validator instead

2023-04-04 18:56 UTC, lucas-jacques commented on web/app/Models/Waiter.ts
> +  public id: number
No need for an id when you extend from the ValyentBaseModel

2023-04-04 18:56 UTC, lucas-jacques commented on web/app/Models/Waiter.ts
> +  public id: number
A cuid is generated

2023-04-04 18:56 UTC, lucas-jacques commented on web/database/migrations/1680560694313_waiters.ts
> +      table.increments('id')
When you use the ValyentBaseModel, it becomes a string
`      table.string().primary()`

2023-04-04 18:56 UTC, lucas-jacques commented on web/resources/views/components/modals/error_modal.edge
> +      <p class="text-sm font-medium text-red-800"> {{content}}</p>
Formatting

2023-04-04 18:56 UTC, lucas-jacques commented on web/resources/views/components/modals/success_modal.edge
> +      <p class="text-sm font-medium text-green-800"> {{content}}</p>
No need for two modals. Make a component for both modal to reuse html

2023-04-04 18:56 UTC, lucas-jacques commented on web/resources/views/components/modals/success_modal.edge
> +      <p class="text-sm font-medium text-green-800"> {{content}}</p>
Add an component class in index.css if needed

2023-04-04 18:56 UTC, lucas-jacques commented on web/resources/views/pages/waitlist.edge
>                class="w-full h-12 px-4 text-gray-200 bg-transparent border-none rounded-l-2xl focus:outline-none focus:ring-offset-gray-700 focus:ring-2 focus:ring-blue-500"><button
Use input component already  provided

2023-04-04 19:11 UTC, alexisbouchez commented on web/resources/views/components/modals/success_modal.edge
> +      <p class="text-sm font-medium text-green-800"> {{content}}</p>
These components should not be called modals, but notifications.

2023-04-05 10:22 UTC, alexisbouchez approved these changes

2023-04-05 10:23 UTC, alexisbouchez approved these changes

2023-04-05 10:24 UTC, alexisbouchez approved these changes

2023-04-05 10:29 UTC, alexisbouchez approved these changes

2023-04-05 11:19 UTC, lucas-jacques approved these changes

2023-04-05 11:19 UTC, merged